//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterSex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialProducts
    {
        public int id { get; set; }
        public Nullable<int> idMaterial { get; set; }
        public Nullable<int> idProduct { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Partners Partners { get; set; }
        public virtual Products Products { get; set; }
    }
}
