//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterSex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.HistoryMaterial = new HashSet<HistoryMaterial>();
            this.MaterialProducts = new HashSet<MaterialProducts>();
        }
    
        public int id { get; set; }
        public Nullable<int> idType { get; set; }
        public string Name { get; set; }
        public Nullable<int> idSupplier { get; set; }
        public Nullable<int> Amount { get; set; }
        public string EdIzmer { get; set; }
        public string Description { get; set; }
        public string ImageMaterial { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> MinAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryMaterial> HistoryMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialProducts> MaterialProducts { get; set; }
        public virtual MaterialTypes MaterialTypes { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
