//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterSex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.SkladUsers = new HashSet<SkladUsers>();
        }
    
        public int id { get; set; }
        public string FIO { get; set; }
        public Nullable<System.DateTime> DateOfBirthday { get; set; }
        public string Pasport { get; set; }
        public string Rekvisits { get; set; }
        public Nullable<bool> isMerried { get; set; }
        public string Helth { get; set; }
        public Nullable<int> idRole { get; set; }
    
        public virtual Roles Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkladUsers> SkladUsers { get; set; }
    }
}
